"""empty message

Revision ID: 42612a7b5486
Revises: 10aeb2bc7623
Create Date: 2023-09-23 12:56:46.509086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42612a7b5486'
down_revision = '10aeb2bc7623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
