"""empty message

Revision ID: adb77c4913ac
Revises: d664f469cc62
Create Date: 2023-09-23 18:55:33.545786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb77c4913ac'
down_revision = 'd664f469cc62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends_table',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('friend_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], name='friends_table_friend_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='friends_table_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'friend_id', name='friends_table_pkey')
    )
    # ### end Alembic commands ###
